cat("ex a ----------------\n")
A = c(6, 9, 7, 3, 6, 7, 9, 6, 3, 6, 6, 7, 1, 9, 1)
cat("i   ->\n")
print(A == 6)
cat("ii  ->\n")
print(A >= 6)
cat("iii ->\n")
print(A < (6 + 2))
cat("iv  ->\n")
print(A != 6)
cat("\nex b ----------------\n")
B = array(A[-1:-3], dim = c(2, 2, 3))
print(B)
cat("i   ->\n")
print(B <= (6 / 2 + 4))
cat("ii  ->\n")
print((B + 2) <= (6 / 2 + 4))

cat("\nex c ----------------\n")
C = diag(10)
print(C == 0)
cat("\nex d ----------------\n")
print(any(B <= (6 / 2 + 4)))
print(all(B <= (6 / 2 + 4)))
print(any((B + 2) <= (6 / 2 + 4)))
print(all((B + 2) <= (6 / 2 + 4)))
cat("\nex e ----------------\n")

print(any(diag(C == 0)));
